import { HttpException, HttpStatus, Injectable } from '@nestjs/common';
import { validate } from 'class-validator';
import crypto from 'crypto';
import jwt from 'jsonwebtoken';
import { EntityManager, type EntitySchemaWithMeta, type InferClassEntityDB, type InferKyselyDB } from '@mikro-orm/mysql';
import { SECRET } from '../config';
import { CreateUserDto, LoginUserDto, UpdateUserDto } from './dto';
import { User } from './user.entity';
import { IUserRO } from './user.interface';
import { UserRepository } from './user.repository';
import { entities } from '../entities.generated';

// Re-derive the generated `Database` type with entity/property naming so the
// typed Kysely query below can use class and property names instead of the
// underlying table/column names.
type PluginOpts = { tableNamingStrategy: 'entity'; columnNamingStrategy: 'property' };
type Database = InferKyselyDB<Extract<(typeof entities)[number], EntitySchemaWithMeta>, PluginOpts>
  & InferClassEntityDB<(typeof entities)[number], PluginOpts>;

@Injectable()
export class UserService {
  constructor(
    private readonly userRepository: UserRepository,
    private readonly em: EntityManager,
  ) {}

  async findAll(): Promise<User[]> {
    return this.userRepository.findAll();
  }

  async findOne(loginUserDto: LoginUserDto): Promise<User | null> {
    const findOneOptions = {
      email: loginUserDto.email,
      password: crypto.createHmac('sha256', loginUserDto.password).digest('hex'),
    };

    return this.userRepository.findOne(findOneOptions);
  }

  async create(dto: CreateUserDto): Promise<IUserRO> {
    // check uniqueness of username/email — uses typed Kysely via the
    // `Database` type generated by `mikro-orm discovery:export`, with
    // entity/property names instead of table/column names
    const { username, email, password } = dto;
    const kysely = this.em.getKysely<Database>({
      tableNamingStrategy: 'entity',
      columnNamingStrategy: 'property',
    });
    const { count } = await kysely
      .selectFrom('User')
      .select(eb => eb.fn.countAll<number>().as('count'))
      .where(eb => eb.or([eb('username', '=', username), eb('email', '=', email)]))
      .executeTakeFirstOrThrow();

    if (count > 0) {
      throw new HttpException(
        {
          message: 'Input data validation failed',
          errors: { username: 'Username and email must be unique.' },
        },
        HttpStatus.BAD_REQUEST,
      );
    }

    // create new user
    const user = new User(username, email, password);
    const errors = await validate(user);

    if (errors.length > 0) {
      throw new HttpException(
        {
          message: 'Input data validation failed',
          errors: { username: 'Userinput is not valid.' },
        },
        HttpStatus.BAD_REQUEST,
      );
    } else {
      await this.em.persist(user).flush();
      return this.buildUserRO(user);
    }
  }

  async update(id: number, dto: UpdateUserDto) {
    const user = await this.userRepository.findOneOrFail(id);
    this.em.assign(user, dto);
    await this.em.flush();

    return this.buildUserRO(user);
  }

  async delete(email: string) {
    return this.userRepository.nativeDelete({ email });
  }

  async findById(id: number): Promise<IUserRO> {
    const user = await this.userRepository.findOne(id);

    if (!user) {
      const errors = { User: ' not found' };
      throw new HttpException({ errors }, 401);
    }

    return this.buildUserRO(user);
  }

  async findByEmail(email: string): Promise<IUserRO> {
    const user = await this.userRepository.findOneOrFail({ email });
    return this.buildUserRO(user);
  }

  generateJWT(user: User) {
    const today = new Date();
    const exp = new Date(today);
    exp.setDate(today.getDate() + 60);

    return jwt.sign(
      {
        email: user.email,
        exp: exp.getTime() / 1000,
        id: user.id,
        username: user.username,
      },
      SECRET,
    );
  }

  private buildUserRO(user: User): IUserRO {
    return {
      user: {
        bio: user.bio,
        email: user.email,
        image: user.image,
        token: this.generateJWT(user),
        username: user.username,
      },
    };
  }
}
