// This file was generated by MikroORM CLI. Do not edit manually.
// Re-run `mikro-orm discovery:export` to update.

import { Article } from './article/article.entity';
import { Comment } from './article/comment.entity';
import { Tag } from './tag/tag.entity';
import { User } from './user/user.entity';
import { EntityManager as DriverEntityManager } from '@mikro-orm/mysql';

export const entities = [
  Article,
  Comment,
  Tag,
  User,
] as const;

export type Database = typeof entities;

export type EntityManager = DriverEntityManager & { '~entities': Database };
export const EntityManager = DriverEntityManager;
