// This file was generated by MikroORM CLI. Do not edit manually.
// Re-run `mikro-orm discovery:export` to update.

import { Article } from './article/article.entity';
import { Comment } from './article/comment.entity';
import { Tag } from './tag/tag.entity';
import { User } from './user/user.entity';
import type { EntitySchemaWithMeta, InferKyselyDB, InferClassEntityDB } from '@mikro-orm/mysql';

export const entities = [
  Article,
  Comment,
  Tag,
  User,
] as const;

export type Database = InferKyselyDB<Extract<(typeof entities)[number], EntitySchemaWithMeta>>
  & InferClassEntityDB<(typeof entities)[number]>;
